version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    depends_on:
      - "rest"
    volumes:
      - /templates/app/templates
      - ./web.py:/app/web.py
    environment:
      - "REST_URL=http://rest:8000"
  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app